version: 2
jobs:
  build:
    docker:
      - image: docker:18.02.0-ce-git
      - image: circleci/postgres:9.5
        environment:
        - POSTGRES_USER: postgres
        - POSTGRES_DB: db
    steps:
      - run: apk update && apk add curl curl-dev

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      - checkout

      - run: cp backend.env.dist backend.env

      - run: docker-compose run server flake8 backend

      - run: docker-compose run python manage.py test
#      - run: coverage run ./manage.py test
#      - run: coverage xml && curl -s https://codecov.io/bash | bash -
